const initialBlogPosts = [
    { day: 1, title: "Our First Day's Adventure!", content: ["Wow, what an incredible start to our journey! Day 1 was packed with excitement.", "We began by exploring the bustling local market, sampling exotic fruits and spices. The vibrant colors and sounds were truly unforgettable.", "In the afternoon, we hiked to a nearby viewpoint. The panorama from the top was breathtaking, stretching out across valleys and distant mountains. We even spotted some local wildlife!"], images: ["https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg?auto=compress&cs=tinysrgb&w=600", "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=60"], comments: [{user: "Traveler1", text: "Sounds amazing!"}, {user: "ExplorerX", text: "Great photos!"}] },
    { day: 2, title: "Exploring the Ancient Ruins", content: ["Day 2 took us back in time as we visited the ancient ruins. The history embedded in the stones was palpable.", "Our guide shared fascinating stories about the civilization that once thrived here, explaining the significance of the different structures.", "Walking through the old city walls and imagining life centuries ago was a truly moving experience. We took lots of pictures!"], images: ["https://images.pexels.com/photos/31803424/pexels-photo-31803424/free-photo-of-spectacular-view-of-ancient-amphitheater-in-athens.jpeg?auto=compress&cs=tinysrgb&w=600", "https://images.pexels.com/photos/3873681/pexels-photo-3873681.jpeg?auto=compress&cs=tinysrgb&w=600"], comments: [] },
    { day: 3, title: "A Relaxing Day by the Lake", content: ["After two busy days, Day 3 was dedicated to relaxation by the serene lake.", "We found a quiet spot, enjoyed a picnic lunch, and simply soaked in the peaceful atmosphere. The water was crystal clear and calm.", "Later, we rented a small boat and paddled around the lake, enjoying the reflections of the sky and trees on the surface. A perfect day to recharge."], images: ["https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=60", "https://images.pexels.com/photos/417074/pexels-photo-417074.jpeg?auto=compress&cs=tinysrgb&w=600"], comments: [{user: "NatureLover", text: "So peaceful."}] },
    { day: 4, title: "Cultural Immersion: Cooking Class", content: ["Today was all about food and culture! We participated in a traditional cooking class.", "We learned to prepare several local dishes using fresh ingredients sourced from a nearby farm. The aroma was amazing!", "Cooking alongside local chefs was a fun and educational experience. And of course, the best part was enjoying the delicious meal we prepared ourselves!"], images: ["https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=60", "https://images.pexels.com/photos/954677/pexels-photo-954677.jpeg?auto=compress&cs=tinysrgb&w=600"], comments: [] },
    { day: 5, title: "Hiking to the Waterfall", content: ["An early start for a hike to the famous waterfall. The trail wound through lush forest, filled with the sounds of birds.", "The final view of the waterfall cascading down the rocks was spectacular and worth the effort of the hike.", "We spent some time enjoying the cool mist and taking photos before making our way back down. A truly refreshing end to this part of the trip."], images: ["https://images.unsplash.com/photo-1501675423372-9bfa95849e62?auto=format&fit=crop&w=800&q=60", "https://images.pexels.com/photos/68632/pexels-photo-68632.jpeg?auto=compress&cs=tinysrgb&w=600"], comments: [] }
];

export default initialBlogPosts;

// Note: The addBlogPost and deleteBlogPost functions from the original
// file will be implemented using React state management (e.g., useState)
// within the main App component or context. 